version: '3.9'

# Last Compilation: 01 November at 01:00 UTC

services:
  esportshelper:
    image: redr00t/esportshelper:latest
    restart: unless-stopped
    container_name: esportshelper
    ports:
      - '6080:6080'
    shm_size: 2g
    volumes:
      - ./config.yaml:/home/alpine/Desktop/EsportsHelper/config.yaml