version: "3.8"
services:
  # Last Update: 08/02/2024 (2.3.2)
  esportshelper:
    image: redr00t/esportshelper:latest
    container_name: esportshelper
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./docker-config:/config
      - ./config.yaml:/esportshelper/config.yaml
    ports:
      - 3000:3000
    shm_size: "2gb"
