version: "3.9"

# Latest version compiled: v2.3.1 (Linux AMD64/ARM64/ARMv7)

services:
  esportshelper:
    image: redr00t/esportshelper:latest
    container_name: EsportsHelper
    restart: unless-stopped
    shm_size: 2g
    volumes:
      - ./config.yaml:/app/config.yaml
