delay: 600
headless: False
username: "exampleaccount"
password: "examplepassword"
connectorDropsUrl: ""
nickName: "examplenickname"
maxStream: 4
briefLogLength: 10
language: "en_US"
autoSleep: True
mode: "safe"
isDockerized: True